# Generated by Django 6.0.2 on 2026-02-10 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('storm', 'Storm'), ('flood', 'Flood'), ('snow', 'Snowfall'), ('fog', 'Heavy Fog'), ('heat', 'Extreme Heat'), ('ice', 'Ice/Freezing')], max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('severe', 'Severe')], max_length=20)),
                ('location_name', models.CharField(max_length=200)),
                ('center_lat', models.FloatField(help_text='Center latitude')),
                ('center_lon', models.FloatField(help_text='Center longitude')),
                ('radius_km', models.FloatField(default=50, help_text='Affected radius in km')),
                ('description', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(db_index=True, max_length=20, unique=True)),
                ('current_lat', models.FloatField(blank=True, help_text='Latitude', null=True)),
                ('current_lon', models.FloatField(blank=True, help_text='Longitude', null=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('current_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='alerts.driver')),
            ],
            options={
                'ordering': ['license_plate'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('critical', 'Critical'), ('standard', 'Standard')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('acknowledged', 'Acknowledged')], default='pending', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alerts.driver')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alerts.truck')),
                ('weather_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alerts.weatherevent')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('weather_event', 'truck')},
            },
        ),
    ]
